service:
  statistic:
    uri: http://${STATISTIC_SERVICE_DOMAIN:localhost}:8091
  shortener:
    uri: http://${SHORTENER_SERVICE_DOMAIN:localhost}:8092
  user:
    uri: http://${USER_SERVICE_DOMAIN:localhost}:8093

spring:
  cloud:
    gateway:
#      routes:
#        - id: statistic_id
#          url: http://localhost:8081
#          predicates:
#          - Path: /statistics/**
