version: "3"

services:
  user-service:
    build:
      context: ../
      dockerfile: user-impl/Dockerfile
    container_name: user-service
    ports:
      - 8093:8093
    environment:
      - BROKERS=kafka:29092
      - ZK_NODES=zookeeper
      - MONGO_DB_HOST=mongo-db
      - MONGO_URI=mongodb://mongo-db:27017/user-ms-db
    depends_on:
      - zookeeper
      - kafka
      - schema-registry
      - kafka-connect
      - ksqldb-server
      - mongo-db

