version: "3"

services:
  statistic-service:
    build:
      context: ../
      dockerfile: statistic-impl/Dockerfile
    container_name: statistic-service
    ports:
      - 8091:8091
    environment:
      - BROKERS=kafka:29092
      - ZK_NODES=zookeeper
      - MONGO_DB_HOST=mongo-db
    depends_on:
      - zookeeper
      - kafka
      - schema-registry
      - kafka-connect
      - ksqldb-server
      - mongo-db