server:
  port: 8091

spring:
  data:
    mongodb:
      host: ${MONGO_DB_HOST:localhost}:27017

kafka:
  bootstrap:
    servers: ${BROKERS:localhost:9092}

  consumer:
    group-id: statistic-service

#spring.cloud.stream.bindings.input1.binder: kafka
