server:
  port : 8082

spring.cloud.stream:
  bindings:
    input.consumer.application-id: url-shortener
    output.contentType: application/json
    shortener-viewed.destination: shortener-viewed
    #  destination: shortener-viewed
    #  producer:
    #    headerMode: raw
    #    #useNativeEncoding: true
    shortener-document.destination: shortener-document
    shortener-changed.destination: shortener-changed

  kafka.streams:
    binder:
      brokers: localhost #192.168.99.100
      configuration:
        commit.interval.ms: 1000
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerd
